-- InnerCompass Mini Database Schema
-- This schema defines the tables for journal entries and reflection outputs

-- Table: journal_entries
-- Stores raw journal entry text from users
CREATE TABLE journal_entries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  entry_text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Table: journal_outputs
-- Stores the validated JSON reflection output from the LLM
CREATE TABLE journal_outputs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  entry_id UUID NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  output JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes for performance
CREATE INDEX idx_journal_entries_user_id ON journal_entries(user_id);
CREATE INDEX idx_journal_outputs_entry_id ON journal_outputs(entry_id);
CREATE INDEX idx_journal_outputs_user_id ON journal_outputs(user_id);

-- Notes:
-- - user_id references Supabase's built-in auth.users table
-- - entry_text stores the raw journal content
-- - output stores the validated JSON reflection as JSONB
-- - UUIDs are auto-generated by Supabase
-- - ON DELETE CASCADE ensures that when a user is deleted, their data is also deleted
